name: MSYS2
on:
  pull_request:
    branches:
      - master
jobs:
  msys2-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: xz mingw-w64-x86_64-gcc automake autoconf make git pkgconf mingw-w64-x86_64-gettext gettext-devel mingw-w64-x86_64-openssl libtool zip
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          architecture: x64
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/lib3270"
          latest: true
          fileName: "mingw-lib3270.tar.xz"   
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/libipc3270"
          latest: true
          fileName: "mingw-libipc3270.tar.xz"   
      - name: CI-Build
        run: |
          ./win/ci-build.sh
      - uses: ncipollo/release-action@v1
        with:
          tag: 5.2
          artifacts: "*.zip,*.jar"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
